### ISSUE TITLE
Add the estimated Degiro fee to the UI

### ISSUE THREAD

**Issue by Rawd2020** [Rawd2020/degiro_share_purchase_calculator#2]
# Summary
Currently, only the estimated maximum purchasable shares (not account for financial transaction tax) is displayed as a result on the calculator. This is despite the fact that we do in fact calculate the total fees to be paid. This fee should be displayed in the UI along with the estimated number of shares purchasable lost to fees.

# Tasks
- [ ] Add the total fees paid to the UI.
- [ ] Change the "Result" UI element to say "Estimated shares purchasable".
- [ ] Include in the new UI the number of potential shares purchasable lost to fees.
