### ISSUE TITLE
Allow for parsing of the ETF fee table

### ISSUE THREAD

**Issue by Rawd2020** [Rawd2020/degiro_share_purchase_calculator#3]
# Summary
Currently we only allow the user to calculate the estimated shares purchasable for "STOCKS, LEVERAGED PRODUCTS, ETNS, WARRANTS, & ADRS". The code should be expanded to include ETFS.

# Tasks
- [ ] Create an __updateETFFees() method in the DegiroFees class to update a new etfFees attribute.
- [ ] Add a call to this new method in parseFees() in feeSchdualParser.py.
- [ ] Create a GUI dropdown menu to allow the user to swap between the UI for the current fee calculator, and a new view for the ETF calculator.
