### ISSUE TITLE
Add support for inputting financial transaction tax cost

### ISSUE THREAD

**Issue by Rawd2020** [Rawd2020/degiro_share_purchase_calculator#4]
# Summary
Currently it is not possible to input the tax percentage of financial transaction tax that may reduce the maximum shares purchasable by a user. A UI element similar to the other entry fields on the calculator is needed to allow the user to enter this value. It also needs to be accounted for in the maxShares() formula.

# Tasks
- [ ] Create a UI Entry() field to allow the use to enter in the financial tax rate on the transaction.
- [ ] Create a UI Entry() field to allow the use to enter in the max financial tax cap on the transaction.
- [ ] Update the maxShares() formula to use these new values.
