### ISSUE TITLE
Add a currency selector & conversion system

### ISSUE THREAD

**Issue by Rawd2020** [Rawd2020/degiro_share_purchase_calculator#5]
# Summary
Currently the calculator is ambiguous in terms of the currency it is working in. Also, the fee per share scraped from the fee schedule PDF may require a conversion. Therefore, a currency selector should be added to the GUI, and the necessary conversions completed.

# Tasks
- [ ] Add a currency selector dropdown menu to the GUI
- [ ] Research how to do currency conversion in PY3
- [ ] Add code to ensure that the fee per share is converted to the correct currency as required
